<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\fondo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
	<PackageReference Include="DnsClient" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\fondo.png" />
  </ItemGroup>

</Project>
