<Project Sdk="Microsoft.NET.Sdk">

  <!-- ====== Propiedades generales ====== -->
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <!-- ====== NuGet ====== -->
  <ItemGroup>
    <PackageReference Include="MongoDB.Bson"  Version="3.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
    <PackageReference Include="DnsClient"      Version="1.6.1" />
  </ItemGroup>

  <!-- ====== Recursos WPF ======
       * Todo lo que haya en Images\*.jpg  o Images\*.png queda embebido.
       * No necesitas añadir uno por uno.                        -->
  <ItemGroup>
    <Resource Include="Images\*.jpg" />
    <Resource Include="Images\*.png" />
  </ItemGroup>

</Project>
